begin;
do $$
declare actor uuid:=gen_random_uuid();host uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();
pa bigint; ph bigint; agency bigint; room uuid; event uuid; req uuid:=gen_random_uuid();
month date:=(date_trunc('month',current_date)-interval '1 month')::date; receipt jsonb; denied boolean:=false;
begin
 insert into auth.users(id,email,raw_user_meta_data)values(actor,actor||'@test.invalid','{}'),(host,host||'@test.invalid','{}'),(outsider,outsider||'@test.invalid','{}');
 select public_id into pa from public.profiles where id=actor;
 select public_id into ph from public.profiles where id=host;
 insert into public.admin_roles(user_id,role)values(actor,'owner');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 agency:=public.create_agency(pa,'Rollback settlement test');
 room:=public.create_room('Rollback settlement test');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',host,'role','authenticated')::text,true);
 perform public.agency_action(agency,'request',null);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 perform public.agency_action(agency,'accept',ph);
 perform set_config('role','postgres',true);
 insert into public.gift_catalog(id,name,price,is_active,diamond_source_type)values('settlement-test-'||actor,'Settlement fixture',1000,true,'FIXED_GIFT');
 insert into public.gift_events(request_id,sender_id,recipient_id,room_id,gift_id,amount,diamond_source_type,quantity,created_at)
 values(gen_random_uuid(),actor,host,room,'settlement-test-'||actor,1000,'FIXED_GIFT',1,month+interval '1 day') returning id into event;
 insert into public.diamond_lots(user_id,source_type,source_reference,diamonds_amount)values(host,'FIXED_GIFT',event,1000);
 update public.profiles set gold=0,diamonds=1000 where id=host;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',host,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 begin perform public.dashboard_monthly_finalize(ph,month,req);exception when insufficient_privilege then denied:=true;end;
 assert denied,'Host could finalize own settlement';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 denied:=false;
 begin perform public.dashboard_monthly_finalize(ph,month,req);exception when raise_exception then if sqlerrm<>'settlement compensation incomplete' then raise;end if;denied:=true;end;
 assert denied,'Diamonds cleared before compensation';
 receipt:=public.dashboard_monthly_save_compensation(ph,month,100,jsonb_build_object(agency::text,20));
 assert receipt->'settlement'->>'status'='ready','Compensation not ready';
 receipt:=public.dashboard_monthly_finalize(ph,month,req);
 assert receipt->'settlement'->>'status'='settled','Settlement not finalized';
 assert (receipt->'settlement'->>'diamonds_earned')::bigint=1000,'Lost historical earned diamonds';
 assert (receipt->'settlement'->>'host_salary')::numeric=100,'Lost host salary';
 assert (receipt->'settlement'->>'coins_generated')::bigint=300,'Wrong conversion';
 assert (receipt->'agencies'->0->>'agent_commission')::numeric=20,'Lost commission';
 perform public.dashboard_monthly_finalize(ph,month,req);
 perform set_config('role','postgres',true);
 assert (select diamonds=0 and gold=300 from public.profiles where id=host),'Wrong wallet or duplicate conversion';
 assert (select count(*) from public.diamond_redemptions where user_id=host)=1,'Duplicate redemption';
 assert (select count(*) from public.dashboard_audit where actor_id=actor and action='settlements.finalize')=1,'Duplicate finalize audit';
 assert (select agency_target=1000 from public.monthly_settlement_agencies where agency_id=agency),'Lost agency target';
end$$;
rollback;
select 'PASS: owner-only close, compensation-before-clearing, 30% conversion, preserved salary/commission/targets, idempotency; fixtures rolled back' result;
