-- Production contracts only. All users, balances, roles and rows are ephemeral.
-- No migrations are applied. Both success and failure end in transaction rollback.
begin;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); pa bigint; pb bigint;
 request uuid:=gen_random_uuid(); purchase jsonb; again jsonb; before_gold bigint; after_gold bigint;
 recharge record; pkg uuid; agency bigint; ticket uuid;
begin
 insert into auth.users(id,aud,role,email) values(a,'authenticated','authenticated',a::text||'@test.invalid'),(b,'authenticated','authenticated',b::text||'@test.invalid');
 update public.profiles set gold=200000,diamonds=100,silver_coins=1000,country_code='IQ',country_name='Iraq' where id=a;
 select public_id into pa from public.profiles where id=a;
 select public_id into pb from public.profiles where id=b;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 begin update public.profiles set vip_level=8 where id=a;raise exception 'self VIP grant allowed';exception when insufficient_privilege then null;end;
 begin update public.profiles set gold=999999 where id=b;raise exception 'other wallet mutation allowed';exception when insufficient_privilege then null;end;
 begin insert into public.admin_roles(user_id,role) values(a,'admin');raise exception 'self admin grant allowed';exception when insufficient_privilege then null;end;
 begin perform public.create_agency(pa,'Unauthorized agency');raise exception 'unauthorized agency creation allowed';exception when raise_exception then if sqlerrm<>'not authorized' then raise;end if;end;
 purchase:=public.purchase_store_item('f1',request);again:=public.purchase_store_item('f1',request);
 if purchase->>'id'<>again->>'id' then raise exception 'store idempotency failed';end if;
 select gold into before_gold from public.profiles where id=a;
 if before_gold<>197500 then raise exception 'store price was not authoritative';end if;
 perform public.equip_store_item('f1','frames');
 begin perform public.equip_store_item('c1','cars');raise exception 'unowned equipment allowed';exception when raise_exception then if sqlerrm<>'valid ownership required' then raise;end if;end;
 perform public.purchase_store_item('vip1',gen_random_uuid());
 if (public.social_profile(pa,false)->>'vip_level')::integer<>1 then raise exception 'VIP entitlement not granted by purchase';end if;
 purchase:=public.claim_reward('daily');again:=public.claim_reward('daily');
 if purchase->>'already_claimed'<>'false' or again->>'already_claimed'<>'true' then raise exception 'daily reward duplicate guard failed';end if;
 select gold into after_gold from public.profiles where id=a;
 if after_gold<>before_gold-63000+300 then raise exception 'daily reward credited more than once';end if;
 begin perform public.claim_reward('follow_two');raise exception 'unearned reward allowed';exception when raise_exception then if sqlerrm<>'task incomplete' then raise;end if;end;
 begin perform public.claim_recharge_reward('tier_9_9');raise exception 'unearned recharge reward allowed';exception when raise_exception then if sqlerrm<>'monthly recharge requirement not met' then raise;end if;end;
 perform public.social_action(pb,'follow');
 if jsonb_array_length(public.social_list('following'))<>1 then raise exception 'follow list contract failed';end if;
 perform public.social_profile(pb,true);
 perform public.social_action(pb,'request');
 begin perform public.social_action(pb,'accept');raise exception 'self accepted outgoing friendship';exception when raise_exception then if sqlerrm<>'incoming request required' then raise;end if;end;
 begin perform public.claim_couple_reward();raise exception 'unearned couple award allowed';exception when raise_exception then if sqlerrm<>'previous week top three required' then raise;end if;end;
 perform public.couple_action(pb,'request');
 begin perform public.couple_action(pb,'accept');raise exception 'self accepted outgoing couple';exception when raise_exception then if sqlerrm<>'incoming request required' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform public.social_action(pa,'accept');perform public.couple_action(pa,'accept');
 if jsonb_array_length(public.social_list('friends'))<>1 or jsonb_array_length(public.social_list('visitors'))<>1 then raise exception 'friend/visitor contract failed';end if;
 if exists(select 1 from public.store_purchases where user_id=a) or exists(select 1 from public.wallet_transactions where user_id=a) then raise exception 'financial rows visible to another user';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 ticket:=public.submit_support_ticket('feedback','Rollback-only integration feedback');
 if ticket is null then raise exception 'support ticket not created';end if;
 update public.user_notifications set read_at=now() where user_id=a;
 begin update public.user_notifications set description='forged notification' where user_id=a;raise exception 'notification forgery allowed';exception when insufficient_privilege then null;end;
 select id into pkg from public.recharge_packages where is_active order by price_usd,id limit 1;
 select * into recharge from public.create_recharge_request(pkg);
 begin perform public.approve_recharge_request(recharge.request_id);raise exception 'self recharge approval allowed';exception when raise_exception then if sqlerrm<>'not authorized' then raise;end if;end;
 select gold into before_gold from public.profiles where id=a;
 perform set_config('role','postgres',true);
 insert into public.admin_roles(user_id,role) values(b,'admin');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 perform public.approve_recharge_request(recharge.request_id);
 begin perform public.approve_recharge_request(recharge.request_id);raise exception 'recharge credited twice';exception when raise_exception then if sqlerrm<>'request is not pending' then raise;end if;end;
 agency:=public.create_agency(pb,'Rollback integration agency');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 select gold into after_gold from public.profiles where id=a;
 if after_gold<>before_gold+recharge.gold_amount then raise exception 'recharge approval ledger mismatch';end if;
 perform public.agency_action(agency,'request',null);
 begin perform public.agency_action(agency,'accept',pa);raise exception 'agency self admission allowed';exception when raise_exception then if sqlerrm<>'not authorized' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'role','authenticated')::text,true);
 perform public.agency_action(agency,'accept',pa);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'role','authenticated')::text,true);
 if public.agency_state()->'agency'->>'id'<>agency::text then raise exception 'agency state mismatch';end if;
 perform public.agency_action(agency,'leave',null);
 perform public.social_action(pb,'block');
 if jsonb_array_length(public.social_list('friends'))<>0 then raise exception 'block did not remove friendship';end if;
 perform public.couple_action(pb,'end');
 perform set_config('role','postgres',true);
end $$;
rollback;
select 'PASS: server commerce/VIP/rewards, relationships, visitors, agency authorization, support/notification RLS, admin-only recharge approval and idempotency; fixtures rolled back' as regression;
