import React,{useEffect,useState} from 'react';
import type {User as AuthUser} from '@supabase/supabase-js';
import {ChevronRight,ShieldCheck,Link,Mail,Phone,RefreshCw} from 'lucide-react';
import {supabase} from '../../services/supabase';
import {linkGoogleAccount} from '../../services/nativeAuth';
import {registerOverlay} from '../../services/overlayNavigation';
export function AccountSecurityScreen({onBack}:{onBack:()=>void}) {
 const [account,setAccount]=useState<AuthUser|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [email,setEmail]=useState(''),[phone,setPhone]=useState(''),[code,setCode]=useState(''),[pendingPhone,setPendingPhone]=useState(''),[unlink,setUnlink]=useState(false);
 useEffect(()=>{const layer=registerOverlay(onBack);return layer.remove},[onBack]);
 const load=async()=>{setLoading(true);setError('');try{const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw error||new Error();setAccount(data.user)}catch{setError('تعذر تحميل أمان الحساب. حاول مرة أخرى.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await action()}catch{setError('تعذر إتمام الطلب. تحقق من الاتصال وتفعيل طريقة الربط، ثم حاول مرة أخرى.')}finally{setBusy(false)}};
 const google=account?.identities?.find(identity=>identity.provider==='google');
 const mask=(value:string)=>value.includes('@')?value.replace(/^(.).*(@.*)$/,'$1••••$2'):value.length>4?`•••• ${value.slice(-4)}`:value;
 return <div dir="rtl" className="min-h-screen bg-[#f5f6f7] text-slate-800 pb-28"><header className="flex items-center gap-3 p-4 border-b border-slate-200"><button type="button" onClick={onBack} aria-label="الرجوع إلى الإعدادات" className="w-11 h-11 flex items-center justify-center"><ChevronRight/></button><h1 className="font-bold">أمان الحساب والربط</h1></header><div className="p-4 space-y-4">
 <section className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4 flex gap-3"><ShieldCheck className="text-emerald-600 shrink-0"/><p className="text-sm leading-6">احتفظ بطريقة دخول مؤكدة لحسابك. لا تشارك رمز التحقق مع أي شخص.</p></section>
 {loading?<p role="status" className="text-center p-6">جارٍ تحميل معلومات الربط…</p>:!account?<button type="button" onClick={()=>void load()} className="rounded-xl bg-white p-4 w-full flex gap-2 justify-center"><RefreshCw size={18}/>إعادة المحاولة</button>:<>
 <section className="rounded-2xl bg-white p-4 space-y-4"><h2 className="font-bold flex gap-2"><Link size={19}/>طرق الدخول المرتبطة</h2><div className="flex justify-between gap-3 items-center"><div><p className="font-semibold text-sm">Google</p><p className="text-xs text-slate-500 mt-1 break-all" dir="ltr">{google?mask(String(google.identity_data?.email||account.email||'حساب مرتبط')):'غير مربوط'}</p></div>{google?<span className="text-xs rounded-full bg-emerald-50 text-emerald-700 px-3 py-2">مربوط</span>:<button type="button" disabled={busy} onClick={()=>void run(linkGoogleAccount)} className="text-sm text-emerald-700 rounded-xl bg-emerald-50 px-4 py-3 disabled:opacity-50">ربط Google</button>}</div>
 {google&&<><button type="button" disabled={busy||!account.phone_confirmed_at} onClick={()=>setUnlink(true)} className="text-sm text-rose-700 disabled:text-slate-400 py-2">إلغاء ربط Google</button><p className="text-xs text-slate-500 leading-5">لتغيير حساب Google، اربط رقم هاتف وأكّده أولاً، ثم ألغِ الربط وأضف حساب Google الجديد.</p></>}
 </section>
 <section className="rounded-2xl bg-white p-4 space-y-3"><h2 className="font-bold flex gap-2"><Phone size={19}/>رقم الهاتف</h2><p className="text-sm text-slate-500" dir="ltr">{account.phone?`${mask(account.phone)} • ${account.phone_confirmed_at?'مؤكد':'بانتظار التأكيد'}`:'غير مربوط'}</p>
 <form onSubmit={event=>{event.preventDefault();void run(async()=>{const next=phone.trim();if(!/^\+[1-9]\d{7,14}$/.test(next)){setError('أدخل رقم الهاتف مع رمز الدولة، مثل +964.');return}const {error}=await supabase.auth.updateUser({phone:next});if(error)throw error;setPendingPhone(next);setNotice('أُرسل طلب التحقق. أدخل الرمز الذي يصلك لتأكيد الرقم.');})}} className="space-y-3"><label className="block text-xs text-slate-600">ربط أو تغيير رقم الهاتف<input dir="ltr" type="tel" autoComplete="tel" value={phone} onChange={event=>setPhone(event.target.value)} required placeholder="+964…" className="mt-2 block w-full border border-slate-200 rounded-xl p-3 text-sm bg-slate-50"/></label><button disabled={busy||Boolean(pendingPhone)} className="w-full p-3 rounded-xl bg-emerald-600 text-white text-sm disabled:opacity-50">إرسال رمز التحقق</button></form>
 {pendingPhone&&<form onSubmit={event=>{event.preventDefault();void run(async()=>{const {error}=await supabase.auth.verifyOtp({phone:pendingPhone,token:code.trim(),type:'phone_change'});if(error)throw error;setPendingPhone('');setCode('');await load();setNotice('تم تأكيد رقم الهاتف.');})}} className="space-y-3"><label className="block text-xs">رمز التحقق<input value={code} onChange={event=>setCode(event.target.value)} inputMode="numeric" autoComplete="one-time-code" required dir="ltr" className="mt-2 w-full p-3 rounded-xl border border-slate-200"/></label><button disabled={busy} className="w-full p-3 bg-emerald-50 text-emerald-700 rounded-xl">تأكيد الرقم</button><button type="button" disabled={busy} onClick={()=>{setPendingPhone('');setCode('');setNotice('')}} className="w-full p-2 text-sm text-slate-500">تغيير الرقم المدخل</button></form>}
 </section>
 <section className="rounded-2xl bg-white p-4 space-y-3"><h2 className="font-bold flex gap-2"><Mail size={19}/>البريد الإلكتروني</h2><p dir="ltr" className="text-sm text-slate-500 break-all">{account.email?mask(account.email):'غير مضاف'}</p><form onSubmit={event=>{event.preventDefault();void run(async()=>{const {error}=await supabase.auth.updateUser({email:email.trim()});if(error)throw error;setEmail('');setNotice('أُرسل طلب تغيير البريد. افتح رسائل التأكيد؛ يبقى البريد الحالي حتى اكتمال التحقق.');})}} className="space-y-3"><label className="block text-xs text-slate-600">البريد الجديد<input type="email" autoComplete="email" dir="ltr" required value={email} onChange={event=>setEmail(event.target.value)} className="mt-2 w-full p-3 rounded-xl bg-slate-50 border border-slate-200 text-sm"/></label><button disabled={busy} className="w-full p-3 rounded-xl bg-slate-100 text-sm disabled:opacity-50">طلب تغيير البريد</button></form><p className="text-xs text-slate-500">تغيير البريد لا يغيّر حساب Google المربوط.</p></section>
 </>}
 {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
 {unlink&&<section role="dialog" aria-label="تأكيد إلغاء الربط" className="rounded-2xl bg-white border border-rose-100 p-4 space-y-3"><p className="text-sm">بعد إلغاء الربط، استخدم رقم الهاتف المؤكد للدخول إلى حسابك.</p><button type="button" disabled={busy} onClick={()=>void run(async()=>{const {data,error}=await supabase.auth.getUser();if(error||!data.user?.phone_confirmed_at)throw error||new Error();const identity=data.user.identities?.find(item=>item.provider==='google');if(!identity)throw new Error();const result=await supabase.auth.unlinkIdentity(identity);if(result.error)throw result.error;setUnlink(false);await load();setNotice('تم إلغاء ربط Google.');})} className="p-3 text-rose-700 bg-rose-50 rounded-xl w-full">تأكيد إلغاء ربط Google</button><button type="button" disabled={busy} onClick={()=>setUnlink(false)} className="p-3 w-full">إلغاء</button></section>}
 </div></div>;
}
