import React, { useEffect, useState } from 'react';
import { useApp } from '../../context/AppContext';
import { MicrophoneSeat } from '../rooms/MicrophoneSeat';
import { RoomUserProfileModal } from '../rooms/RoomUserProfileModal';
import { GiftStoreModal } from '../rooms/GiftStoreModal';
import {RoomInfoModal} from '../rooms/RoomInfoModal';
import { RoomManagementModal } from '../rooms/RoomManagementModal';
import { GiftOverlayAnimation } from '../common/GiftOverlayAnimation';
import { User } from '../../types';
import { supabase } from '../../services/supabase';
import { useRoomAudioContext } from '../../context/RoomAudioContext';
import { Mic, MicOff, Volume2, VolumeX, ChevronRight, Settings, Gift, Hand, Send, Minimize2, LogOut, X, Users } from 'lucide-react';

export const VoiceRoomScreen: React.FC = () => {
  const {activeRoom,user,leaveRoom,takeSeat,leaveSeat,isMyMicMuted,toggleMyMic,toggleRaiseHand,isHandRaised,isSpeakerOn,toggleSpeaker,activeGiftOverlay,setActiveSubScreen,setSelectedChatUser,reportError}=useApp();
  const [infoOpen,setInfoOpen]=useState(false);
  const [giftOpen,setGiftOpen]=useState(false); const [managementOpen,setManagementOpen]=useState(false); const [exitOpen,setExitOpen]=useState(false); const [selectedUser,setSelectedUser]=useState<User|null>(null);
  const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState(''); const [sending,setSending]=useState(false); const [micBusy,setMicBusy]=useState(false);
  const {connected,enableMicrophone,speakingIds}=useRoomAudioContext();
  useEffect(()=>{if(!activeRoom)return;const roomId=activeRoom.id;setMessages([]);setSelectedUser(null);let disposed=false;const load=async()=>{const {data,error}=await supabase.from('room_messages').select('*').eq('room_id',roomId).order('created_at',{ascending:false}).limit(100);if(disposed)return;if(error)reportError('تعذر تحميل دردشة الغرفة.');else setMessages(prev=>[...new Map([...(data||[]).reverse(),...prev].map(m=>[m.id,m])).values()].sort((a,b)=>new Date(a.created_at).getTime()-new Date(b.created_at).getTime()).slice(-100))};void load();const channel=supabase.channel(`chat:${roomId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'room_messages',filter:`room_id=eq.${roomId}`},event=>{if(!disposed)setMessages(prev=>prev.some(m=>m.id===event.new.id)?prev:[...prev.slice(-99),event.new])}).subscribe();return()=>{disposed=true;void supabase.removeChannel(channel)}},[activeRoom?.id]);
  if(!activeRoom)return null;
  const mySeat=activeRoom.seats.find(s=>s.user?.authId===user.authId);
  const handleMic=async()=>{if(micBusy)return;if(!mySeat){reportError('اختر مقعداً أولاً لتشغيل المايكروفون.');return}setMicBusy(true);try{if(isMyMicMuted)await enableMicrophone();await toggleMyMic()}catch(error){const name=error&&typeof error==='object'&&'name'in error?String(error.name):'';if(name==='NotAllowedError'||name==='SecurityError')reportError('تم رفض إذن المايكروفون. اسمح لتوتي شات باستخدام المايكروفون من إعدادات الهاتف ثم حاول مجدداً.');else reportError('تعذر تشغيل المايكروفون. تحقق من الإذن والاتصال ثم حاول مجدداً.')}finally{setMicBusy(false)}};
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim()||sending||activeRoom.chatEnabled===false)return;setSending(true);try{const {error}=await supabase.from('room_messages').insert({room_id:activeRoom.id,content:text.trim()});if(error)throw error;setText('')}catch{reportError('تعذر إرسال الرسالة. حاول مجدداً.')}finally{setSending(false)}};
  const clickSeat=(index:number)=>{const seat=activeRoom.seats[index];if(!seat)return;if(seat.user)setSelectedUser(seat.user);else if(!seat.isLocked)void takeSeat(index);else reportError('هذا المقعد مقفل.')};
  const minimizeRoom=()=>{setExitOpen(false);setActiveSubScreen('home')}; const confirmLeaveRoom=async()=>{setExitOpen(false);await leaveRoom()};
  return <div dir="rtl" className="min-h-screen bg-[#080914] text-white relative flex flex-col pb-24"><div className="absolute inset-0 pointer-events-none"><img src={activeRoom.coverImage} alt="" className="w-full h-full object-cover opacity-25"/></div>
    <header className="relative p-4 flex gap-3 items-center border-b border-white/10"><button onClick={()=>setExitOpen(true)} aria-label="خيارات الغرفة" className="p-2 rounded-full bg-white/10"><ChevronRight/></button><button type="button" onClick={()=>setInfoOpen(true)} className="flex-1 text-right min-w-0" aria-label="معلومات الغرفة"><h1 className="font-bold truncate">{activeRoom.title}</h1><p className="text-xs text-slate-300">ID: {activeRoom.id}</p></button><button onClick={()=>setInfoOpen(true)} className="flex items-center gap-1 px-2 py-1.5 rounded-full bg-white/10 text-xs" aria-label="الموجودون في الغرفة"><Users size={15}/>{activeRoom.usersCount}</button>{activeRoom.canModerate&&<button onClick={()=>setManagementOpen(true)} aria-label="إدارة الغرفة" className="p-2 rounded-full bg-white/10"><Settings/></button>}</header>
    <div className="relative p-4"><div className="rounded-2xl bg-black/25 border border-white/10 p-3 mb-5"><p className="text-[11px] text-amber-300 mb-1">إشعار الغرفة</p><p className="text-sm text-slate-200">{(activeRoom.welcomeMessage ?? activeRoom.description)||'أهلاً وسهلاً بكم في الغرفة ❤️'}</p></div><div className="grid grid-cols-4 gap-x-2 gap-y-5">{activeRoom.seats.map(seat=><MicrophoneSeat key={seat.seatIndex} seat={{...seat,isSpeaking:Boolean(seat.user?.authId&&speakingIds.includes(seat.user.authId))&&!seat.isMuted}} onSeatClick={clickSeat} isCurrentUserSeat={seat.user?.authId===user.authId}/>)}</div><p className="text-xs text-slate-400 mt-4">اضغط مقعداً فارغاً للجلوس أو الانتقال إليه، واضغط صورة مستخدم لعرض ملفه بدون مغادرة الغرفة.</p></div>
    <div className="relative mx-4 mt-auto border-t border-white/10 pt-3 pb-2"><div className="max-h-48 overflow-y-auto space-y-2 px-1" aria-live="polite">{messages.length?messages.map(m=><p key={m.id} className="text-sm break-words"><span className="text-teal-300 font-semibold">{m.sender_display_name||'مستخدم'}: </span>{m.content}</p>):<p className="text-slate-400 text-xs">ابدأ الحديث برسالة.</p>}</div>{activeRoom.chatEnabled===false&&<p role="status" className="text-xs text-slate-400 mt-2">الدردشة العامة متوقفة في هذه الغرفة.</p>}<form onSubmit={send} className="mt-3 flex gap-2 items-center bg-black/35 rounded-full px-3 py-1.5 border border-white/10"><input aria-label="رسالة الغرفة" disabled={activeRoom.chatEnabled===false} value={text} onChange={e=>setText(e.target.value)} maxLength={1000} placeholder={activeRoom.chatEnabled===false?'الدردشة متوقفة من إدارة الغرفة':'اكتب رسالة…'} className="min-w-0 flex-1 bg-transparent outline-none p-2 text-sm"/><button disabled={sending||!text.trim()||activeRoom.chatEnabled===false} className="p-2 text-teal-300 disabled:opacity-40"><Send size={20}/></button></form></div>
    <footer className="fixed bottom-0 inset-x-0 max-w-md mx-auto z-20 bg-[#080914]/95 border-t border-white/10 flex justify-around items-center p-4"><button aria-label={isMyMicMuted ? "تشغيل المايكروفون" : "كتم المايكروفون"} onClick={handleMic} disabled={micBusy} className="p-3 rounded-full bg-white/10">{isMyMicMuted?<MicOff className="text-rose-400"/>:<Mic className="text-teal-300"/>}</button>{mySeat&&<button onClick={()=>void leaveSeat(mySeat.seatIndex)} className="text-xs text-slate-300">مغادرة المقعد</button>}<button aria-label={isSpeakerOn ? "كتم سماعة الغرفة" : "تشغيل سماعة الغرفة"} onClick={toggleSpeaker} className="p-3 rounded-full bg-white/10">{isSpeakerOn?<Volume2/>:<VolumeX/>}</button><button aria-label="إرسال هدية" onClick={()=>setGiftOpen(true)} className="p-3 rounded-full bg-gradient-to-r from-purple-600 to-pink-500"><Gift/></button><button aria-label={isHandRaised ? "إنزال اليد" : "رفع اليد"} onClick={toggleRaiseHand} className={`p-3 rounded-full ${isHandRaised?'bg-amber-500':'bg-white/10'}`}><Hand/></button></footer>
    {exitOpen&&<div className="fixed inset-0 z-[120] bg-black/65 flex items-end justify-center" onClick={()=>setExitOpen(false)}><div role="dialog" aria-modal="true" aria-label="خيارات الغرفة" className="w-full max-w-md rounded-t-2xl bg-[#11131f] p-3 pb-[max(0.75rem,env(safe-area-inset-bottom))]" onClick={e=>e.stopPropagation()}><div className="flex justify-between items-center mb-2"><h2 className="font-bold text-sm">خيارات الغرفة</h2><button aria-label="إغلاق خيارات الغرفة" onClick={()=>setExitOpen(false)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-2"><button onClick={minimizeRoom} className="w-full flex justify-center gap-2 rounded-2xl bg-emerald-500 text-slate-950 font-bold text-sm p-3"><Minimize2/>تصغير الغرفة</button><button onClick={()=>void confirmLeaveRoom()} className="w-full flex justify-center gap-2 rounded-2xl bg-rose-600 font-bold text-sm p-3"><LogOut/>الخروج من الغرفة</button></div></div></div>}
    {activeRoom.giftEffectsEnabled!==false&&activeGiftOverlay&&<GiftOverlayAnimation overlayData={activeGiftOverlay}/>}<RoomUserProfileModal isOpen={Boolean(selectedUser)} targetUser={selectedUser} onClose={()=>setSelectedUser(null)} onOpenMore={()=>{if(!selectedUser)return;setSelectedChatUser(selectedUser);setSelectedUser(null);setActiveSubScreen('user_detail_profile')}}/><GiftStoreModal isOpen={giftOpen} onClose={()=>setGiftOpen(false)} room={activeRoom} onRechargeClick={()=>{setGiftOpen(false);setActiveSubScreen('recharge')}}/><RoomInfoModal isOpen={infoOpen} onClose={()=>setInfoOpen(false)} room={activeRoom} onSelectMember={setSelectedUser}/><RoomManagementModal isOpen={managementOpen} onClose={()=>setManagementOpen(false)} room={activeRoom}/>
  </div>;
};
