
import React,{useState} from 'react';
import {Search,ShieldCheck,ChevronRight,Lock,AlertCircle} from 'lucide-react';
const groups=['نظرة عامة','المستخدمون','الغرف','المحتوى','الهدايا','المتجر','المستويات وVIP','الشارات','CP','الوكالات','وكلاء الشحن','المحفظة والخزينة','التسوية الشهرية','الفعاليات','الإعلانات','الدعم','الإشعارات','الصلاحيات','سجل التدقيق','إعدادات النظام'];
export function AdminPreview(){
 const [search,setSearch]=useState('');const [active,setActive]=useState<string|null>(null);
 const [action,setAction]=useState('');const [month,setMonth]=useState<'current'|'past'>('current');
 const filtered=groups.filter(x=>x.includes(search));
 return <div dir="rtl" className="min-h-screen bg-[#f6f7f7] pb-32 text-slate-900"><header className="p-5 bg-[#0e302a] text-white"><span className="text-xs text-emerald-100">مساحة عرض مستقلة عن التطبيق</span><h1 className="text-xl font-black mt-2">لوحة تحكم TotiChat</h1><p className="text-xs leading-6 text-slate-200 mt-2">نموذج UI فقط. لا يمنح صلاحيات ولا يغيّر أرصدة أو مستخدمين أو استحقاقات.</p></header>
 <div className="m-3 bg-amber-50 border border-amber-200 p-4 rounded-2xl text-xs text-amber-900 leading-6"><ShieldCheck size={18} className="inline ml-2"/>حساب Owner محمي. جميع العمليات الحساسة تحتاج هوية مؤكدة وصلاحية من الخادم وسجل تدقيق وسبب واضح.</div>
 {!active?<main className="p-3"><label className="flex min-h-12 px-3 items-center gap-2 border bg-white rounded-xl"><Search size={17}/><input className="flex-1 min-w-0 outline-none text-sm" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالوحدات"/></label><div className="grid grid-cols-2 gap-2 mt-3">{filtered.map((a,i)=><button type="button" key={a} onClick={()=>{setActive(a);setAction('')}} className="bg-white rounded-2xl border p-4 text-right min-h-24"><b className="block text-xs text-emerald-800 mb-2">وحدة الإدارة</b><span className="font-bold text-sm">{a}</span></button>)}</div></main>:
 <main className="p-3 space-y-3"><button className="min-h-11 flex gap-2 items-center text-sm" type="button" onClick={()=>{setActive(null);setAction('')}}><ChevronRight size={18}/> جميع الوحدات</button><section className="bg-white border rounded-2xl p-4"><h2 className="font-black text-lg">{active}</h2><p className="text-xs mt-2 text-slate-500">واجهات القائمة والبحث والتعديل والاعتماد تتطلب خدمة حقيقية وصلاحيات.</p>{active==='التسوية الشهرية'?<div className="mt-3"><div className="flex gap-2">{(['current','past'] as const).map(x=><button type="button" key={x} onClick={()=>setMonth(x)} className={'min-h-11 rounded-lg px-3 text-xs '+(month===x?'bg-[#1b7050] text-white':'bg-slate-100')}>{x==='current'?'الشهر الحالي':'الأشهر السابقة'}</button>)}</div><p className="text-xs text-amber-800 mt-3">الاستحقاقات تُسجل قبل تصفير الماس التشغيلي الشهري، وتبقى غير المدفوعة محفوظة. لا توجد أرقام محسوبة هنا.</p><div className="mt-3 grid grid-cols-2 gap-2">{['قيد الاحتساب','قيد المراجعة','معتمدة','مستحقة','مدفوعة','تعثرت'].map(y=><span className="bg-slate-50 rounded-lg p-2 text-xs border" key={y}>{y}</span>)}</div></div>:null}
 <div className="grid grid-cols-2 gap-2 mt-5">{['قائمة السجلات','بحث وفلاتر','عرض التفاصيل','إنشاء/تعديل','سجل التدقيق','إجراء حساس'].map(x=><button type="button" key={x} onClick={()=>setAction(x)} className="min-h-12 rounded-xl border bg-slate-50 p-2 text-xs font-bold">{x}</button>)}</div>
 {action&&<div role="status" className="bg-amber-50 text-amber-900 p-4 mt-4 rounded-xl"><b>{action}</b><p className="text-xs leading-6 mt-1">هذا إجراء مرئي في نموذج الإدارة فقط، ولا يتم تنفيذه قبل التحقق من صلاحية المستخدم وسجل التدقيق وخدمة الخادم.</p></div>}
 </section></main>}
 </div>;
}
