
import React,{useState} from 'react';
import {ChevronLeft,WifiOff,Lock,Search,AlertCircle,Mic,Gift,Users,CheckCircle2} from 'lucide-react';
type Tab='flows'|'states'|'rtl'|'components'|'tasks';
type State='normal'|'loading'|'empty'|'offline'|'error'|'permission'|'disabled';
const flows=[['home','S010 · الرئيسية'],['rooms','S013 · استكشاف الغرف'],['voice','S020 · الغرفة الصوتية'],['gifts','S025 · اختيار الهدايا'],['profile','S044 · الملف الشخصي'],['messages','S039 · الرسائل']];
const states:State[]=['normal','loading','empty','offline','error','permission','disabled'];
const stateLabels=['عادي','تحميل','فارغ','انقطاع','خطأ','إذن','تعطيل'];
const names=['زر أساسي','زر ثانوي','حقل','رمز OTP','تبويبات','بطاقة غرفة','مقعد مايك','تحكم صوت','بلاطة هدية','تأكيد هدية','مشغّل موسيقى','فقاعة رسالة','بطاقة مستخدم','مؤشر مستوى','رصيد','عنصر متجر','حوار تأكيد','إشعار','حالات النظام','لوحة إذن','هيكل تحميل','فلتر','صورة مستخدم','مؤثر احتفالي'];
const sections=[['flows','التنقل'],['states','الحالات'],['rtl','اللغات'],['components','المكونات'],['tasks','التقدم']] as const;
export function AuditLab({onNavigate}:{onNavigate:(key:string)=>void}){
 const [tab,setTab]=useState<Tab>('flows');
 const [state,setState]=useState<State>('normal');
 const [rtl,setRtl]=useState(true);
 const [scale,setScale]=useState(100);
 const [query,setQuery]=useState('');
 const [message,setMessage]=useState('');
 const [checks,setChecks]=useState<string[]>([]);
 const panel='bg-white rounded-2xl p-4 border border-slate-200 shadow-sm';
 const action='min-h-12 w-full rounded-xl bg-[#1b7050] text-white text-sm font-bold';
 return <div className="min-h-screen bg-[#f6f7f7] text-slate-900 pb-24" dir="rtl">
 <header className="bg-[#1b7050] text-white p-4"><div className="flex items-center gap-3">
 <img src="/assets/images/toti_falcon_logo_1790422919580.jpg" alt="الشعار الحالي" className="w-16 h-16 rounded-xl object-contain bg-black"/>
 <div><p className="text-xs text-emerald-100">مختبر UI/UX — بيانات تجريبية</p><h1 className="font-black text-lg">TotiChat · Design Review</h1><p className="text-xs text-emerald-100">دون تغيير الألوان أو الهوية الأصلية</p></div></div>
 <div className="mt-4 grid grid-cols-3 gap-2 text-center text-[11px] font-bold"><span className="bg-white/15 rounded-lg p-2">109 تاسكات</span><span className="bg-white/15 rounded-lg p-2">70 شاشة</span><span className="bg-white/15 rounded-lg p-2">34 اختبار</span></div></header>
 <nav className="sticky top-12 bg-white border-b z-10 flex overflow-x-auto" aria-label="اختيار نوع التدقيق">{sections.map(([id,label])=><button key={id} onClick={()=>{setTab(id);setMessage('')}} type="button" aria-pressed={tab===id} className={'min-w-[64px] flex-1 min-h-12 text-xs font-bold border-b-[3px] '+(tab===id?'border-[#1b7050] text-[#1b7050]':'border-transparent text-slate-500')}>{label}</button>)}</nav>
 <div className="p-3 space-y-3">
 {tab==='flows'&&<section className={panel}><h2 className="font-bold">UX-002 · خريطة التنقل القابلة للفتح</h2><p className="text-xs text-slate-500 mt-1 mb-3">افتح أي واجهة من التطبيق الأصلي عبر القائمة. العودة من قائمة المعاينة العلوية.</p><div className="space-y-2">{flows.map(([id,label],i)=><div key={id}><button type="button" onClick={()=>onNavigate(id)} className="bg-slate-50 rounded-xl border border-slate-200 w-full min-h-14 px-4 flex items-center justify-between gap-3"><span className="text-sm font-bold">{label}</span><ChevronLeft size={17}/></button>{i<flows.length-1&&<p aria-hidden="true" className="text-center text-[#1b7050]">↓</p>}</div>)}</div><p className="text-xs text-slate-500 mt-3">دخول → صفحة رئيسية → غرفة → مايك/دردشة → اختيار هدية → مراجعة → إرسال → خروج. هذه خطة UX لا إثبات Backend.</p></section>}
 {tab==='states'&&<section className={panel}><h2 className="font-bold">UX-005 · حالة الشاشة</h2><p className="text-xs text-slate-500 mt-1">سبع نماذج مستقلة، بدون عمليات حقيقية.</p><div className="flex gap-2 overflow-x-auto my-3">{states.map((s,i)=><button type="button" key={s} onClick={()=>{setState(s);setMessage('')}} aria-pressed={state===s} className={'min-h-11 rounded-xl px-3 whitespace-nowrap text-xs font-bold '+(state===s?'bg-[#1b7050] text-white':'bg-slate-100')}>{stateLabels[i]}</button>)}</div>
 <div className="border border-dashed border-slate-300 rounded-xl min-h-[180px] bg-slate-50 p-4 flex flex-col justify-center items-center text-center gap-3" role="status">
 {state==='loading'?<><div className="h-6 w-full rounded bg-slate-200 animate-pulse"/><div className="h-4 w-3/4 rounded bg-slate-200 animate-pulse"/><div className="h-4 w-1/2 rounded bg-slate-200 animate-pulse"/></>:state==='normal'?<><img src="/assets/images/room_cover_majlis_1790226059300.jpg" alt="" className="w-20 h-20 rounded-xl object-cover"/><strong>سهرة الأصدقاء</strong><button onClick={()=>onNavigate('voice')} className={action}>فتح الغرفة</button></>:<><div className="text-[#1b7050]">{state==='offline'?<WifiOff/>:state==='permission'?<Lock/>:state==='empty'?<Search/>:<AlertCircle/>}</div><strong>{state==='empty'?'لا توجد نتائج':state==='offline'?'لا يوجد اتصال بالإنترنت':state==='error'?'حدث خطأ مؤقت':state==='permission'?'إذن المايك مرفوض':'هذا الخيار غير متاح'}</strong><p className="text-xs text-slate-500">توضيح السبب والخطوة التالية قبل أي إجراء</p>{state!=='disabled'&&<button type="button" className={action} onClick={()=>setMessage('محاولة عرض فقط — لا توجد خدمة حقيقية')}>إعادة المحاولة</button>}</>}
 {message&&<p className="text-xs text-amber-800">{message}</p>}</div>
 <div className="mt-4 text-xs text-slate-600 leading-7">المصفوفة تشمل الدخول، البحث، الغرف، الهدايا، الموسيقى، الدردشة، الحساب، المحفظة والإعدادات. تغطية كل حالة في كل شاشة ما زالت قيد العمل.</div></section>}
 {tab==='rtl'&&<section className={panel}><h2 className="font-bold">UX-003 · عينة RTL / LTR</h2><div className="flex gap-2 my-3"><button type="button" className={action} onClick={()=>setRtl(true)}>RTL عربي</button><button type="button" className={action} onClick={()=>setRtl(false)}>LTR English</button></div>
 <div dir={rtl?'rtl':'ltr'} className="border rounded-xl p-4 bg-slate-50 space-y-2 text-sm"><strong>{rtl?'غرفة الأصدقاء':'Friends Voice Room'}</strong><p>{rtl?'معرّف الغرفة':'Room ID'}: <b dir="ltr">AB-203014</b></p><p><bdi>VIP 10</bdi> · {rtl?'المايك مفتوح':'Microphone enabled'}</p></div><div className="mt-4 space-y-2">{['السهم واتجاه الرجوع','معرفات وأرقام مختلطة','ترتيب التبويبات','المسافات ونصوص الأزرار','عدم عكس الشعار'].map(x=><label key={x} className="min-h-11 flex items-center gap-3 text-xs"><input type="checkbox" className="w-5 h-5 accent-emerald-700" checked={checks.includes(x)} onChange={()=>setChecks(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])}/>{x}</label>)}</div><p className="text-xs text-slate-500 mt-2">اختيار هذه الخانات ملاحظات للمراجع، وليس نجاحاً موثقاً.</p></section>}
 {tab==='components'&&<><section className={panel}><h2 className="font-bold">UX-006–011 · الهوية الحالية</h2><p className="text-xs text-slate-600 leading-6 mt-2">الشعار واللون الموجودان في TotiChat محفوظان؛ UX-009 مستثنى بأمر المالك. UX-008 أيقونة المشغّل معلقة حتى الموافقة.</p><p className="font-bold text-sm mt-3">مقياس نص تجريبي</p><div className="flex gap-2 my-3">{[100,125,150].map(x=><button type="button" key={x} aria-pressed={scale===x} onClick={()=>setScale(x)} className={'min-h-11 flex-1 rounded-lg text-xs '+(scale===x?'bg-[#1b7050] text-white':'bg-slate-100')}>{x}%</button>)}</div><p style={{fontSize:14*scale/100}} className="leading-7">تصميم بسيط وواضح للغرف الصوتية — TotiChat 203014</p><p className="text-xs text-slate-500 mt-3">المقياس 4dp · مسافات 4/8/12/16/20/24/32 · هدف لمس 48dp. غيّر عرض الشاشة 320–430dp من الأعلى.</p></section>
 <section className={panel}><h2 className="font-bold">C01–C24 · فهرس المكونات</h2><input aria-label="بحث المكونات" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو C07" className="w-full min-h-12 border rounded-xl px-3 my-3 text-sm"/><div className="grid grid-cols-2 gap-2">{names.map((name,i)=>({name,id:'C'+String(i+1).padStart(2,'0')})).filter(x=>(x.name+x.id).toLowerCase().includes(query.toLowerCase())).map(x=><div className="rounded-xl p-2 border min-h-14" key={x.id}><span className="block text-[10px] text-[#1b7050] font-bold">{x.id}</span><strong className="text-xs">{x.name}</strong></div>)}</div><p className="text-xs text-slate-500 mt-3">هذه قائمة مواصفات؛ متغيرات Figma القابلة للتعديل لم تكتمل.</p></section></>}
 {tab==='tasks'&&<section className={panel}><h2 className="font-bold">سجل المرحلة الأولى حسب الترتيب</h2><div className="space-y-2 mt-3 text-xs">{[['UX-001','مرجع Dana الحي: معلّق؛ لم تتوفر تجربة مباشرة'],['UX-002','التنقل: خريطة قابلة للمراجعة'],['UX-003','RTL: عينة متاحة، فحص بقية الصفحات مستمر'],['UX-004','قياسات Dana: معلقة إلى حين وصول صور موثوقة'],['UX-005','حالات النظام: نموذج مرئي ومصفوفة'],['UX-006','هوية اجتماعية واضحة مع الحفاظ على الموجود'],['UX-007','عدم تغيير الشعار'],['UX-008','الأيقونة: موافقة مطلوبة'],['UX-009','ألوان جديدة: مستثناة'],['UX-010–012','قياسات وخطوط وفهرس مكونات: مسودات']].map(([a,b])=><div key={a} className="p-3 rounded-xl bg-slate-50 flex gap-3"><span className="font-bold text-[#1b7050] whitespace-nowrap" dir="ltr">{a}</span><span>{b}</span></div>)}</div><p className="mt-3 text-xs text-slate-500">المعاينة لا تؤكد أن المصادقة أو الصوت أو الهدايا أو أي Backend يعمل.</p></section>}
 </div></div>;
}