
import React,{useEffect,useState} from 'react';
import {ChevronRight,Check,Eye,EyeOff,Mail,Phone,ShieldCheck,WifiOff,ArrowLeft,RefreshCw} from 'lucide-react';
type Step='splash'|'methods'|'phone'|'otp'|'email'|'password'|'profile'|'complete';
const countries=[['+964','العراق 🇮🇶'],['+966','السعودية 🇸🇦'],['+971','الإمارات 🇦🇪'],['+962','الأردن 🇯🇴'],['+963','سوريا 🇸🇾'],['+965','الكويت 🇰🇼']];
export function AuthPreview({onComplete}:{onComplete:()=>void}){
 const [step,setStep]=useState<Step>('splash'),[country,setCountry]=useState('+964'),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false);
 const [profileName,setProfileName]=useState(''),[error,setError]=useState(''),[offline,setOffline]=useState(false),[countdown,setCountdown]=useState(60),[notice,setNotice]=useState(''),[terms,setTerms]=useState(false);
 useEffect(()=>{if(step!=='otp'||countdown<=0)return;const t=setTimeout(()=>setCountdown(c=>Math.max(0,c-1)),1000);return()=>clearTimeout(t)},[step,countdown]);
 const go=(s:Step)=>{setError('');setNotice('');setStep(s)};
 const back=()=>{if(step==='otp')go('phone');else if(step==='password')go('email');else go('methods')};
 const phoneSubmit=(e:React.FormEvent)=>{e.preventDefault();if(offline){setError('لا يوجد اتصال بالإنترنت في هذا السيناريو التجريبي.');return}if(!/^0?[0-9]{8,12}$/.test(phone.trim())){setError('أدخل رقم هاتف صحيحاً بدون رمز الدولة.');return}setCountdown(60);go('otp')};
 const otpSubmit=(e:React.FormEvent)=>{e.preventDefault();if(offline){setError('تحقق من الاتصال قبل تأكيد الرمز.');return}if(!/^[0-9]{6}$/.test(otp)){setError('أدخل ستة أرقام.');return}if(otp!=='123456'){setError('رمز تجريبي غير صحيح. جرّب 123456.');return}go('profile')};
 const emailSubmit=(e:React.FormEvent)=>{e.preventDefault();if(!/^[^@ ]+@[^@ ]+\.[^@ ]+$/.test(email.trim())){setError('يرجى كتابة بريد إلكتروني صحيح.');return}go('password')};
 const passwordSubmit=(e:React.FormEvent)=>{e.preventDefault();if(password.length<8){setError('كلمة المرور تتطلب 8 أحرف في هذه المعاينة.');return}go('profile')};
 const profileSubmit=(e:React.FormEvent)=>{e.preventDefault();if(profileName.trim().length<2){setError('الاسم لا يقل عن حرفين.');return}go('complete')};
 const btn='w-full min-h-12 rounded-xl px-4 font-extrabold text-sm bg-[#1b7050] text-white disabled:opacity-50';
 const input='w-full rounded-xl border border-slate-300 bg-white px-4 min-h-12 text-slate-900 text-sm focus-visible:ring-2 focus-visible:ring-emerald-700 outline-none';
 return <div dir="rtl" className="min-h-screen bg-[#f6f7f7] pb-28">
 <header className="flex min-h-14 items-center gap-3 bg-white border-b border-slate-200 px-4">
 <button aria-label="رجوع" className="min-w-12 min-h-12 flex items-center justify-center" type="button" onClick={back}><ChevronRight/></button>
 <div className="flex-1"><b className="text-sm">S001–S009 · معاينة التسجيل</b><p className="text-[11px] text-slate-500">تصميم توضيحي — لا ترسل بيانات حقيقية</p></div><ShieldCheck size={20} className="text-emerald-700"/>
 </header>
 <div className="m-3 rounded-xl bg-amber-50 border border-amber-200 p-3 text-xs leading-6 text-amber-900"><strong>واجهة تجريبية فقط.</strong> لا يوجد إرسال OTP أو تسجيل دخول حقيقي أو تخزين كلمة مرور. استخدم بيانات وهمية.</div>
 <div className="px-4 pb-5 flex items-center justify-between text-xs"><label className="flex gap-2 items-center"><input aria-label="محاكاة انقطاع الشبكة" type="checkbox" checked={offline} onChange={e=>setOffline(e.target.checked)} className="w-5 h-5 accent-emerald-700"/><WifiOff size={15}/>محاكاة انقطاع الاتصال</label><span className="font-bold text-emerald-800">{step}</span></div>
 <main className="mx-3 bg-white rounded-3xl border border-slate-200 shadow-sm p-5 space-y-4">
 {step==='splash'&&<div className="min-h-[390px] flex flex-col justify-center items-center gap-4 text-center">
 <img src="/assets/images/toti_falcon_logo_1790422919580.jpg" className="w-52 h-52 object-contain rounded-3xl" alt="شعار TotiChat الحالي"/>
 <h1 className="font-black text-xl">أهلاً بيك في TotiChat</h1><p className="text-xs text-slate-500">سوالف، صداقات، وغرف صوتية</p><button className={btn} type="button" onClick={()=>go('methods')}>ابدأ</button></div>}
 {step==='methods'&&<><h1 className="font-bold text-xl">أهلاً وسهلاً</h1><p className="text-sm text-slate-500">اختر طريقة تجربة واجهة تسجيل الدخول</p>
 <button className={btn} type="button" onClick={()=>go('phone')}><Phone size={17} className="inline ml-2"/>الدخول برقم الهاتف</button>
 <button className="w-full min-h-12 rounded-xl bg-slate-100 font-bold text-sm" onClick={()=>go('email')} type="button"><Mail size={17} className="inline ml-2"/>الدخول بالبريد</button>
 <p className="text-xs text-slate-500">التسجيل عبر Google غير مفعل في المعاينة. ماكو زر يوهمك أنه اتصل بحسابك.</p>
 <button type="button" className="underline text-xs text-emerald-700" onClick={()=>setTerms(true)}>شروط الاستخدام والخصوصية (نموذج)</button></>}
 {step==='phone'&&<form className="space-y-4" onSubmit={phoneSubmit}><h2 className="font-bold text-lg">رقم الهاتف</h2><label htmlFor="ui-auth-country" className="text-xs font-bold">البلد ورمز الاتصال</label><select id="ui-auth-country" dir="ltr" className={input} value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option value={c[0]} key={c[0]}>{c[1]} {c[0]}</option>)}</select>
 <label htmlFor="ui-auth-phone" className="text-xs font-bold">رقم الهاتف</label><input id="ui-auth-phone" dir="ltr" type="tel" inputMode="tel" autoComplete="off" value={phone} onChange={e=>setPhone(e.target.value)} className={input} placeholder="0770 000 0000"/><button type="submit" className={btn}>الاستمرار إلى رمز التجربة</button></form>}
 {step==='otp'&&<form className="space-y-4" onSubmit={otpSubmit}><h2 className="text-lg font-bold">التحقق من الرقم</h2><p className="text-xs text-slate-500">رمز الاختبار: <b dir="ltr">123456</b> — لم يُرسل SMS</p><label htmlFor="ui-auth-otp" className="text-sm">رمز من 6 أرقام</label><input id="ui-auth-otp" autoComplete="off" inputMode="numeric" maxLength={6} dir="ltr" className={input+' text-center tracking-[.25em] text-lg'} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="000000"/>
 <button type="submit" className={btn}>تأكيد رمز العرض</button><div className="flex gap-2 justify-between text-xs"><button type="button" onClick={()=>go('phone')} className="underline">تعديل الرقم</button><button type="button" disabled={countdown>0} onClick={()=>{setCountdown(60);setNotice('أعدنا تشغيل العد التنازلي فقط؛ لم نرسل رسالة.')}} className="font-bold text-emerald-800 disabled:text-slate-400">{countdown>0?'إعادة المحاولة بعد '+countdown+' ث':'إعادة إرسال تجريبية'}</button></div></form>}
 {step==='email'&&<form className="space-y-4" onSubmit={emailSubmit}><h2 className="font-bold text-lg">البريد الإلكتروني</h2><label htmlFor="ui-auth-email" className="text-sm">البريد</label><input id="ui-auth-email" dir="ltr" type="email" autoComplete="off" value={email} onChange={e=>setEmail(e.target.value)} className={input} placeholder="demo@example.com"/><button type="submit" className={btn}>التالي</button></form>}
 {step==='password'&&<form className="space-y-4" onSubmit={passwordSubmit}><h2 className="font-bold text-lg">كلمة المرور — تجربة فقط</h2><div className="relative"><input aria-label="كلمة مرور تجريبية" type={showPassword?'text':'password'} value={password} autoComplete="off" onChange={e=>setPassword(e.target.value)} className={input} placeholder="8 أحرف على الأقل"/><button type="button" aria-label={showPassword?'إخفاء':'إظهار'} onClick={()=>setShowPassword(v=>!v)} className="absolute left-0 top-0 w-12 h-12 flex items-center justify-center">{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div><button className={btn} type="submit">متابعة</button><button type="button" className="text-xs underline" onClick={()=>setNotice('نموذج استعادة كلمة المرور ما زال غير مكتمل، ولن يرسل أي طلب.')}>نسيت كلمة المرور؟</button></form>}
 {step==='profile'&&<form className="space-y-4" onSubmit={profileSubmit}><h2 className="font-bold text-lg">أكمل ملفك (نموذج)</h2><div className="w-20 h-20 mx-auto rounded-full bg-slate-100 grid place-items-center text-4xl">👤</div><label htmlFor="ui-auth-name" className="text-sm">اسم العرض</label><input id="ui-auth-name" className={input} value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="اسم مستخدم تجريبي" /><p className="text-xs text-slate-500">الصورة اختيارية ولا يتم رفعها بأي مكان.</p><button className={btn} type="submit">إنهاء تجربة التسجيل</button></form>}
 {step==='complete'&&<div className="py-8 flex flex-col items-center gap-4 text-center"><Check size={42} className="text-emerald-700"/><h2 className="font-bold text-lg">نهاية سيناريو التسجيل</h2><p className="text-xs text-slate-500">لم يُنشأ حساب ولم تتغير أي بيانات.</p><button type="button" className={btn} onClick={onComplete}>شاهد واجهة الرئيسية</button></div>}
 {error&&<p role="alert" className="text-xs text-rose-700 rounded-lg p-3 bg-rose-50 border border-rose-200">{error}</p>}
 {notice&&<p role="status" className="text-xs text-amber-900 bg-amber-50 rounded-lg p-3">{notice}</p>}
 </main>
 {terms&&<div role="dialog" aria-modal="true" aria-label="شروط العرض" className="fixed inset-0 z-[990] bg-black/65 grid place-items-center p-5"><div className="bg-white rounded-3xl p-5 max-w-sm w-full space-y-4"><h2 className="font-bold">شروط تجريبية</h2><p className="text-xs leading-7">هذا مو نص سياسة قانونية نهائية. راح نوفر الروابط الحقيقية بعد اعتماد المحتوى القانوني الرسمي.</p><button onClick={()=>setTerms(false)} type="button" className={btn}>إغلاق</button></div></div>}
 </div>;
}