import React,{useEffect,useRef,useState} from 'react';
import {useApp} from '../../context/AppContext';
let savedPosition:{x:number;y:number}|null=null;
export const MinimizedRoomBar:React.FC=()=>{
 const {activeRoom,activeSubScreen,setActiveSubScreen}=useApp();
 const ref=useRef<HTMLButtonElement>(null),drag=useRef<{x:number;y:number;left:number;top:number;moved:boolean}|null>(null),suppressClick=useRef(false);
 const [position,setPosition]=useState(savedPosition);
 const clamp=(x:number,y:number)=>{const box=ref.current?.getBoundingClientRect();return {x:Math.max(8,Math.min(x,window.innerWidth-(box?.width||208)-8)),y:Math.max(8,Math.min(y,(window.visualViewport?.height||window.innerHeight)-(box?.height||72)-8))}};
 const move=(x:number,y:number)=>{const next=clamp(x,y);savedPosition=next;setPosition(next)};
 useEffect(()=>{const resize=()=>{if(savedPosition)move(savedPosition.x,savedPosition.y)};window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);return()=>{window.removeEventListener('resize',resize);window.visualViewport?.removeEventListener('resize',resize)}},[]);
 if(!activeRoom||!activeSubScreen)return null;
 return <button ref={ref} type="button" dir="rtl" aria-label={`العودة إلى غرفة ${activeRoom.title}`} aria-description="اسحب البطاقة لتغيير مكانها، أو استخدم أسهم لوحة المفاتيح" onPointerDown={event=>{if(event.button!==0)return;const box=event.currentTarget.getBoundingClientRect();drag.current={x:event.clientX,y:event.clientY,left:box.left,top:box.top,moved:false};suppressClick.current=false;event.currentTarget.setPointerCapture(event.pointerId)}} onPointerMove={event=>{const start=drag.current;if(!start)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(Math.hypot(dx,dy)>6)start.moved=true;if(start.moved)move(start.left+dx,start.top+dy)}} onPointerUp={event=>{if(drag.current?.moved)suppressClick.current=true;drag.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}} onPointerCancel={()=>{suppressClick.current=true;drag.current=null}} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}setActiveSubScreen(null)}} onKeyDown={event=>{const steps:Record<string,number[]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};const step=steps[event.key];if(!step)return;event.preventDefault();const box=event.currentTarget.getBoundingClientRect();move(box.left+step[0],box.top+step[1])}} style={{touchAction:'none',backgroundImage:`linear-gradient(0deg,rgba(0,0,0,.55),rgba(0,0,0,.25)),url(${JSON.stringify(activeRoom.internalBackground||'/assets/images/room_screen_bg_1790556227206.jpg')})`,backgroundSize:'cover',backgroundPosition:'center',...(position?{left:position.x,top:position.y,bottom:'auto'}:{left:12,bottom:96})}} className="fixed z-[40] w-52 max-w-[65vw] rounded-2xl text-white shadow-xl border border-white/30 p-2 flex items-center gap-2 text-right select-none cursor-grab active:cursor-grabbing focus-visible:outline-emerald-400">
 <img src={activeRoom.coverImage} alt="" draggable={false} className="w-11 h-11 rounded-xl object-cover shrink-0"/><span className="min-w-0 flex-1"><span className="block text-[10px] text-emerald-200">أنت داخل الغرفة الآن</span><span className="block text-sm font-bold truncate">{activeRoom.title}</span></span><span className="text-[11px] bg-white/15 rounded-full px-2 py-2">عودة</span></button>;
};
