import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdtemp,rm}from 'node:fs/promises';import {join}from 'node:path';import {pathToFileURL}from 'node:url';import {JSDOM}from 'jsdom';import React,{act}from 'react';import {createRoot}from 'react-dom/client';
test('confirmed gift refreshes seat value and chat immediately; duplicate realtime delivery adds no duplicate message',async()=>{
 const dom=new JSDOM('<div id="root"></div>');const keys=['window','document','navigator','IS_REACT_ACT_ENVIRONMENT'];const saved=new Map(keys.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));for(const k of keys)Object.defineProperty(globalThis,k,{configurable:true,value:k==='IS_REACT_ACT_ENVIRONMENT'?true:(dom.window as any)[k]});
 let received=0;const feed:any[]=[];const handlers:Function[]=[];
 (globalThis as any).__feedClient={rpc:async(name:string)=>({data:name==='social_profile'?{public_id:1002,display_name:'Recipient',received_gold:received,level:1,vip_level:0}:name==='profile_relationships'?[]:null,error:null}),from:()=>{const q:any={};for(const n of ['select','eq','order','limit'])q[n]=()=>q;q.then=(resolve:any)=>Promise.resolve({data:feed,error:null}).then(resolve);return q},channel:()=>{const ch:any={on:(_kind:any,_filter:any,callback:Function)=>{handlers.push(callback);return ch},subscribe:()=>ch};return ch},removeChannel:async()=>{}};
 const temp=await mkdtemp(join(process.cwd(),'.feed-test-'));let root:ReturnType<typeof createRoot>|undefined;
 try{
 await build({stdin:{contents:`import React from 'react';import {useRoomGiftMessages}from './src/hooks/useRoomGiftMessages';import {useRoomSeatProfile}from './src/hooks/useRoomSeatProfile';const snapshot={id:'1002',authId:'target',name:'Recipient'};export function Harness(){const seat=useRoomSeatProfile(snapshot);const messages=useRoomGiftMessages('room');return React.createElement('div',null,React.createElement('output',null,seat.roomReceivedGold),messages.map(m=>React.createElement('p',{key:m.id},m.content)));}`,resolveDir:process.cwd(),loader:'tsx'},bundle:true,packages:'external',platform:'node',format:'esm',outfile:join(temp,'bundle.mjs'),plugins:[{name:'server',setup(b){b.onResolve({filter:/\/services\/supabase$|^\.\/supabase$/},()=>({path:'supabase',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const supabase=globalThis.__feedClient;'}))}}]});
 const {Harness}=await import(pathToFileURL(join(temp,'bundle.mjs')).href);root=createRoot(dom.window.document.getElementById('root')!);await act(async()=>root!.render(React.createElement(Harness)));
 assert.equal(dom.window.document.querySelector('output')!.textContent,'0');received=350;
 const row={id:'receipt',room_id:'room',sender_name:'Sender',recipient_name:'Recipient',gift_name:'Heart',quantity:7,created_at:new Date().toISOString()};feed.push(row);
 await act(async()=>dom.window.dispatchEvent(new dom.window.CustomEvent('toti:gift-confirmed',{detail:{roomId:'room'}})));
 assert.equal(dom.window.document.querySelector('output')!.textContent,'350');assert.equal(dom.window.document.querySelectorAll('p').length,1);assert.match(dom.window.document.querySelector('p')!.textContent!,/Sender 7 × Heart إلى Recipient/);
 await act(async()=>{handlers.forEach(h=>{h({new:row});h({new:row})})});assert.equal(dom.window.document.querySelectorAll('p').length,1);
 }finally{await act(async()=>root?.unmount());dom.window.close();for(const[k,v]of saved){if(v)Object.defineProperty(globalThis,k,v);else delete(globalThis as any)[k]}delete(globalThis as any).__feedClient;await rm(temp,{recursive:true,force:true})}
});
